apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dermacam
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/Arthrok/backend.git"
    path: "kubernetes"
    targetRevision: main
    kustomize: {}
    directory:
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: dermacam
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
